### ISSUE TITLE
Migration, default value for author.

### ISSUE THREAD

**Issue by HappyZombies** [HappyZombies/4chan-Laravel#8]
https://github.com/HappyZombies/4chan-Laravel/blob/master/app/Http/Controllers/ThreadController.php#L46 

Here we have a ternary operator that checks to see if author is empty or not. If empty, give it a default value of "Anonymous". This default value of "Anonymous" should go in both our thread and comment migration. 

https://github.com/HappyZombies/4chan-Laravel/blob/master/database/migrations/2016_05_04_175648_create_threads_table.php#L20

and

https://github.com/HappyZombies/4chan-Laravel/blob/master/database/migrations/2016_05_08_234835_create_comments_table.php#L19

**Comment by gjrdiesel** [comment]
Are we ok with modifying the existing migration and rerunning with fresh migrations or should this be done another migration?

**Comment by HappyZombies** [comment]
Yes modify the existing migration if you'd like !
